export { HeroCarousel } from "./components/home/HeroSection";
export { AnimeSection } from "./components/home/AnimeSection";
export { LazySection } from "./components/home/AnimeSection";
export { TrendingSection } from "./components/home/AnimeSection";
export { PopularSection } from "./components/home/AnimeSection";
export { TopRatedSection } from "./components/home/AnimeSection";
export { SeasonSection } from "./components/home/AnimeSection";
export { UpcomingSection } from "./components/home/AnimeSection";
export * from "./types/hero";
export * from "./types/section-anime";
export * from "./types/trending";
export * from "./types/popular";
export * from "./types/top-rated";
export * from "./types/season";
export * from "./types/upcoming";

export { getHeroAnime } from "./api/services/home/hero.service";
export { getTrendingAnime } from "./api/services/home/trending.service";
export { getPopularAnime } from "./api/services/home/popular.service";
export { getTopRatedAnime } from "./api/services/home/top-rated.service";
export { getSeasonAnime } from "./api/services/home/season.service";
export { getUpcomingAnime } from "./api/services/home/upcoming.service";
