export { default as AnimeSection } from "./AnimeSection";
export { default as AnimeCard } from "./AnimeCard";
export { default as AnimeSectionSkeleton } from "./AnimeSectionSkeleton";
export { default as LazySection } from "./LazySection";
export { default as TrendingSection } from "./TrendingSection";
export { default as PopularSection } from "./PopularSection";
export { default as TopRatedSection } from "./TopRatedSection";
export { default as SeasonSection } from "./SeasonSection";
export { default as UpcomingSection } from "./UpcomingSection";
